# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/habitrack',
                'doc_host': 'https://doyu.github.io',
                'git_url': 'https://github.com/doyu/habitrack',
                'lib_path': 'habitrack'},
  'syms': {'habitrack.core': {'habitrack.core.foo': ('core.html#foo', 'habitrack/core.py')}}}
