# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/habitrack',
                'doc_host': 'https://doyu.github.io',
                'git_url': 'https://github.com/doyu/habitrack',
                'lib_path': 'habitrack'},
  'syms': { 'habitrack.app': { 'habitrack.app.create_app': ('app.html#create_app', 'habitrack/app.py'),
                               'habitrack.app.main': ('app.html#main', 'habitrack/app.py'),
                               'habitrack.app.toggle_url': ('app.html#toggle_url', 'habitrack/app.py')},
            'habitrack.core': { 'habitrack.core.current_streak': ('core.html#current_streak', 'habitrack/core.py'),
                                'habitrack.core.load_full': ('core.html#load_full', 'habitrack/core.py'),
                                'habitrack.core.save_full': ('core.html#save_full', 'habitrack/core.py'),
                                'habitrack.core.window': ('core.html#window', 'habitrack/core.py')}}}
