"""Item management CLI — `python -m habitrack.admin` (see `DESIGN.md` §5). Called by the `habitrack-items` skill over ssh; no UI in the app.

Docs: https://doyu.github.io/habitrack/admin.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_admin.ipynb.

# %% auto #0
__all__ = ['backup', 'summary', 'mutate', 'main']

# %% ../nbs/02_admin.ipynb #977c059f
import argparse
import json
import shutil
import sys
from datetime import date, datetime
from pathlib import Path

from .app import TZ
from .core import (add_item, display_name, is_archived, load_full, ordered_items,
                            rate_30d, rename_item, save_full, set_archived)

# %% ../nbs/02_admin.ipynb #48094806
def backup(
    path:Path,  # live ledger CSV
) -> Path:
    "Copy the ledger to a `.bak` sibling (overwritten each time) — the only safety net before a mutation."
    bak = path.with_suffix(".bak")
    shutil.copy2(path, bak)
    return bak

# %% ../nbs/02_admin.ipynb #3964627b
def summary(
    path:Path,  # live ledger CSV; must exist
    today:date,  # last day of the 30-day rate window
) -> list:
    "One dict per item in display order: `name` (no marker), `archived`, `rate_30d`."
    if not path.exists():
        raise FileNotFoundError(path)
    full = load_full(path, [], today)
    return [{"name": display_name(c), "archived": is_archived(c), "rate_30d": rate_30d(full, c, today)}
            for c in ordered_items(full)]

# %% ../nbs/02_admin.ipynb #e139e24d
def mutate(
    path:Path,  # live ledger CSV; must exist
    fn,  # pure transform `DataFrame -> DataFrame` from `habitrack.core`
    today:date,  # passed through to `summary`
) -> list:
    "backup -> load -> fn -> atomic save -> re-read check; returns the new summary."
    if not path.exists():
        raise FileNotFoundError(path)
    df = fn(load_full(path, [], today))  # validate before touching disk
    backup(path)
    save_full(df, path)
    if not load_full(path, [], today).equals(df):
        raise RuntimeError(f"re-read mismatch after writing {path}; previous state is in {path.with_suffix('.bak')}")
    return summary(path, today)

# %% ../nbs/02_admin.ipynb #21edd276
def main(
    argv:list=None,  # CLI args; defaults to sys.argv[1:]
) -> int:
    "Subcommands: summary | add NAME | archive NAME | unarchive NAME | rename OLD NEW. JSON on stdout, errors on stderr."
    p = argparse.ArgumentParser(prog="python -m habitrack.admin", description=main.__doc__)
    p.add_argument("--data", type=Path, required=True, help="ledger CSV, e.g. /opt/habitrack/app/data/ledger.csv")
    sub = p.add_subparsers(dest="cmd", required=True)
    sub.add_parser("summary")
    for cmd in ["add", "archive", "unarchive"]:
        sub.add_parser(cmd).add_argument("name")
    r = sub.add_parser("rename")
    r.add_argument("old")
    r.add_argument("new")
    a = p.parse_args(argv)
    ops = {
        "add": lambda df: add_item(df, a.name),
        "archive": lambda df: set_archived(df, a.name, True),
        "unarchive": lambda df: set_archived(df, a.name, False),
        "rename": lambda df: rename_item(df, a.old, a.new),
    }
    today = datetime.now(TZ).date()
    try:
        out = summary(a.data, today) if a.cmd == "summary" else mutate(a.data, ops[a.cmd], today)
    except (ValueError, KeyError, FileNotFoundError, RuntimeError) as e:
        print(f"error: {e.args[0] if e.args else e}", file=sys.stderr)
        return 1
    print(json.dumps(out, ensure_ascii=False))
    return 0

# %% ../nbs/02_admin.ipynb #21f25a5b
if __name__ == "__main__":  # python -m habitrack.admin
    sys.exit(main())
