"""FastHTML web layer — auth, routes, UI (see `DESIGN.md` §4/§6). Ledger logic lives in `00_core.ipynb`.

Docs: https://doyu.github.io/habitrack/app.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_app.ipynb.

# %% auto #0
__all__ = ['DAYS_SHOWN', 'TZ', 'DOW_JA', 'DEFAULT_ITEMS', 'CSS', 'HDRS', 'toggle_url', 'create_app', 'main']

# %% ../nbs/01_app.ipynb #0651c4cd
import os
import threading
import time
from datetime import date, datetime, timedelta
from pathlib import Path
from urllib.parse import quote
from zoneinfo import ZoneInfo

import uvicorn
from fasthtml.common import *

from .core import display_name, is_archived, load_full, ordered_items, rate_30d, rename_item, save_full, set_archived, window

# %% ../nbs/01_app.ipynb #62d08d4e
DAYS_SHOWN = 10
TZ = ZoneInfo("Europe/Helsinki")  # "today" never depends on server-local time (DESIGN.md §7)
DOW_JA = ["月", "火", "水", "木", "金", "土", "日"]
DEFAULT_ITEMS = ["読書", "運動", "執筆", "瞑想", "早起き"]
CSS = """\
:root{--paper:#EFECE3;--paper-line:#CBCABB;--ink:#23272A;--ink-soft:#5B5F58;--amber:#B9822E;--amber-soft:#E9DCC0}
*{box-sizing:border-box}
body{background:var(--paper);color:var(--ink);font-family:'Space Mono',monospace;
     max-width:520px;margin:0 auto;padding:32px 20px 60px}
h1{font-family:'Shippori Mincho',serif;font-size:22px;margin:0 0 20px;
   border-bottom:2px solid var(--ink);padding-bottom:10px}
table{border-collapse:collapse}
td,th{padding:0;text-align:center}
.item-cell{font-family:'Shippori Mincho',serif;font-size:15px;text-align:left;
           padding-right:12px;white-space:nowrap}
.dow{font-size:9px;color:var(--ink-soft)}
.num{font-size:9px;color:#9a9a8c}
.today .num{color:var(--amber);font-weight:700}
input[type=checkbox]{appearance:none;width:20px;height:20px;border:1.5px solid var(--ink-soft);
  border-radius:3px;cursor:pointer;margin:2px 4px}
input[type=checkbox]:checked{background:var(--ink);border-color:var(--ink)}
input[type=checkbox].today-cb{border-color:var(--amber);border-width:2.5px}
.count{font-size:10px;font-weight:700;color:var(--amber);background:var(--amber-soft);
       border-radius:3px;padding:1px 5px;margin-left:6px}
.count.zero{background:none;color:var(--ink-soft)}
.item-cell span,.item-cell s{cursor:text}
.item-cell input[type=text]{font:inherit;width:9em;padding:2px 4px;border:1.5px solid var(--amber);border-radius:3px;background:none}
.err{display:block;font-size:10px;color:#a33}
input[type=password]{font-family:inherit;font-size:15px;padding:6px 8px;
  border:1.5px solid var(--ink-soft);border-radius:3px;background:none}
button{font-family:inherit;font-size:14px;padding:6px 14px;cursor:pointer;
  border:1.5px solid var(--ink);border-radius:3px;background:var(--ink);color:var(--paper)}"""
HDRS = (
    Link(rel="preconnect", href="https://fonts.googleapis.com"),
    Link(
        href="https://fonts.googleapis.com/css2?family=Shippori+Mincho:wght@500;700&family=Space+Mono:wght@400;700&display=swap",
        rel="stylesheet",
    ),
    Style(CSS),
)

# %% ../nbs/01_app.ipynb #9124a3c9
def toggle_url(
    item:str,  # item name — percent-encoded so names may contain ? # % & etc.
    day:date,
) -> str:
    "htmx POST target for one checkbox."
    return f"/toggle/{quote(item, safe='')}/{day.isoformat()}"

# %% ../nbs/01_app.ipynb #0b47dded
def create_app(
    data_path:Path,  # ledger.csv location — outside the static route (DESIGN.md §3)
    password:str,  # login password; must be non-empty
    secret_key:str,  # session cookie signing key; must be non-empty
    https_only:bool=False,  # sess_https_only — production sets this (DESIGN.md §6)
    default_items:list=DEFAULT_ITEMS,  # columns for first-run auto-create
    tz:ZoneInfo=TZ,  # timezone that defines "today"
    static_path:str="static",  # dedicated assets dir; must not contain the ledger
):
    "Build the habitrack FastHTML app; fails fast on empty secrets."
    if not password or not secret_key:
        raise ValueError("password and secret_key must be non-empty")
    expected = password
    lock = threading.Lock()  # serializes toggle read-modify-write (single process)

    def today() -> date:
        return datetime.now(tz).date()

    def auth_before(req, sess):
        if not sess.get("auth"):
            return Redirect("/login")

    app, rt = fast_app(
        before=Beforeware(auth_before, skip=[r"/login"]),
        secret_key=secret_key,
        sess_https_only=https_only,
        static_path=static_path,  # data/ must stay unreachable (DESIGN.md §3)
        hdrs=HDRS,
    )

    def render_table():
        full = load_full(data_path, default_items, today())
        df = window(full, today(), DAYS_SHOWN)
        days = list(df.index)
        t = today()

        header = Tr(
            Th("", cls="item-cell"),
            *[
                Th(Div(DOW_JA[d.weekday()], cls="dow"), Div(str(d.day), cls="num"),
                   cls="today" if d == t else "")
                for d in days
            ],
        )

        rows = [header]
        for item in ordered_items(df):  # active first, archived at the bottom (DESIGN.md §5)
            archived = is_archived(item)
            edit = dict(hx_get=f"/edit/{quote(item, safe='')}", hx_target="closest td", hx_swap="innerHTML")
            if archived:
                label = [S(display_name(item), **edit)]  # struck through, no badge
            else:
                n = round(rate_30d(full, item, today()) * 30)  # checked days in the trailing 30 (DESIGN.md §4)
                label = [Span(item, **edit), Span(f"{n}/30", cls=f"count{' zero' if n == 0 else ''}")]
            cells = [Td(*label, cls="item-cell")]
            for d in days:
                htmx = {} if archived else dict(
                    hx_post=toggle_url(item, d),
                    hx_target="#ledger",
                    hx_swap="outerHTML",
                    hx_disabled_elt="this",
                )
                cells.append(
                    Td(
                        Input(
                            type="checkbox",
                            checked=bool(df.at[d, item]),
                            disabled=archived,
                            cls="today-cb" if d == t else "",
                            **htmx,
                        )
                    )
                )
            rows.append(Tr(*cells))

        return Table(*rows, id="ledger")

    @rt("/")
    def get():
        return Titled("習慣ログ", render_table())  # Titled renders the H1 itself

    @rt("/toggle/{item}/{d}")
    def post(item: str, d: str):
        day = date.fromisoformat(d)
        with lock:  # concurrent toggles must not lose writes
            full = load_full(data_path, default_items, today())
            if item in full.columns and not is_archived(item):  # archived rows are read-only
                if day not in full.index:
                    full.loc[day] = False
                full.at[day, item] = not full.at[day, item]
                full.sort_index(inplace=True)
                save_full(full, data_path)
        return render_table()

    def edit_form(item, value, error=None):
        "Click-to-edit: Enter submits; a leading ~ in the typed name archives, removing it restores (DESIGN.md §5)."
        return Form(
            Input(type="text", name="new", value=value, autofocus=True),
            *([Small(error, cls="err")] if error else []),
            hx_post=f"/rename/{quote(item, safe='')}", hx_target="#ledger", hx_swap="outerHTML",
        )

    @rt("/edit/{item}")
    def get(item: str):
        return edit_form(item, value=item)  # raw column name, so an archived row shows its ~

    @rt("/rename/{item}")
    def post(item: str, new: str = ""):
        new = new.strip()
        want = new.startswith("~")
        base = new[1:] if want else new
        with lock:
            full = load_full(data_path, default_items, today())
            try:
                full = rename_item(full, display_name(item), base)  # validates; keeps the archived state
                full = set_archived(full, base, want)  # then apply what was typed
            except (ValueError, KeyError) as e:
                return edit_form(item, value=new, error=str(e.args[0]))
            save_full(full, data_path)
        return render_table()

    @rt("/login", methods=["GET"])
    def login_page():
        return Titled("習慣ログ", Form(
            Input(type="password", name="password", autofocus=True),
            Button("ログイン"),
            method="post", action="/login",
        ))

    @rt("/login", methods=["POST"])
    def login_submit(sess, password: str = ""):
        if password == expected:
            sess["auth"] = True
            return Redirect("/")
        time.sleep(0.5)  # the entire brute-force defense (DESIGN.md §6)
        return Redirect("/login")

    return app

# %% ../nbs/01_app.ipynb #9c9cdc85
def main(
    data_path:Path,  # ledger.csv location
    static_path:str="static",  # passed through to `create_app`
    host:str="127.0.0.1",  # loopback only; Caddy is the sole public path (DESIGN.md §6)
    port:int=None,  # default: $PORT if set (systemd unit), else 5001
):
    "Entry point: secrets from env (fail-fast on empty), serve on loopback."
    app = create_app(
        data_path,
        password=os.environ.get("HABITRACK_PASSWORD", ""),
        secret_key=os.environ.get("HABITRACK_SECRET_KEY", ""),
        https_only=os.environ.get("HABITRACK_HTTPS_ONLY") == "1",
        static_path=static_path,
    )
    uvicorn.run(app, host=host, port=port or int(os.environ.get("PORT", "5001")))
