"""ledger.csv backend — pure logic and atomic CSV I/O (see `DESIGN.md` §3). The web layer lives in `01_app.ipynb`.

Docs: https://doyu.github.io/habitrack/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['save_full', 'load_full', 'window', 'current_streak']

# %% ../nbs/00_core.ipynb #d1e61017
import os
from datetime import date, timedelta
from pathlib import Path

import pandas as pd

# %% ../nbs/00_core.ipynb #322d3ad4
def save_full(
    df:pd.DataFrame,  # ledger frame — index=date, columns=item names, values=bool
    path:Path):  # live CSV; a .tmp sibling in the same dir is used for the swap
    "Atomic write: a mid-write crash must never corrupt the live file."
    path.parent.mkdir(exist_ok=True)
    tmp = path.with_suffix(".tmp")
    df.to_csv(tmp)
    os.replace(tmp, path)

# %% ../nbs/00_core.ipynb #ca2aa617
def load_full(
    path:Path,  # ledger CSV location
    default_items:list,  # columns for first-run auto-create
    today:date,  # index row for first-run auto-create
) -> pd.DataFrame:
    "Full history; blank cells read as False; auto-creates the CSV on first run."
    if not path.exists():
        df = pd.DataFrame(False, index=pd.Index([today], name="date"),
                          columns=default_items)
        save_full(df, path)
        return df
    df = pd.read_csv(path, index_col=0)
    df = df.fillna(False).astype(bool)
    df.index = pd.Index([date.fromisoformat(d) for d in df.index], name="date")
    return df

# %% ../nbs/00_core.ipynb #f135df05
def window(
    full:pd.DataFrame,  # full history from `load_full`
    today:date,  # last day of the window
    days:int=10,  # window length
) -> pd.DataFrame:
    "Trailing `days`-day view ending today; dates missing from history are False."
    idx = [today - timedelta(days=i) for i in range(days - 1, -1, -1)]
    return full.reindex(pd.Index(idx, name="date"), fill_value=False)

# %% ../nbs/00_core.ipynb #e8018cdb
def current_streak(
    full:pd.DataFrame,  # full history from `load_full`
    item:str,  # column name
    today:date,
) -> int:
    "Consecutive checked days ending today — or yesterday, if today is still unchecked."
    col = full[item]
    d = today
    if not col.get(d, False):  # today unchecked -> streak starts from yesterday
        d -= timedelta(days=1)
    streak = 0
    while col.get(d, False):
        streak += 1
        d -= timedelta(days=1)
    return streak
