"""ledger.csv backend — pure logic and atomic CSV I/O (see `DESIGN.md` §3). The web layer lives in `01_app.ipynb`.

Docs: https://doyu.github.io/habitrack/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['ARCHIVE_PREFIX', 'save_full', 'load_full', 'window', 'is_archived', 'display_name', 'validate_name', 'ordered_items',
           'add_item', 'rename_item', 'set_archived', 'rate_30d']

# %% ../nbs/00_core.ipynb #d1e61017
import os
from datetime import date, timedelta
from pathlib import Path

import pandas as pd

# %% ../nbs/00_core.ipynb #322d3ad4
def save_full(
    df:pd.DataFrame,  # ledger frame — index=date, columns=item names, values=bool
    path:Path):  # live CSV; a .tmp sibling in the same dir is used for the swap
    "Atomic write: a mid-write crash must never corrupt the live file."
    path.parent.mkdir(exist_ok=True)
    tmp = path.with_suffix(".tmp")
    df.to_csv(tmp)
    os.replace(tmp, path)

# %% ../nbs/00_core.ipynb #ca2aa617
def load_full(
    path:Path,  # ledger CSV location
    default_items:list,  # columns for first-run auto-create
    today:date,  # index row for first-run auto-create
) -> pd.DataFrame:
    "Full history; blank cells read as False; auto-creates the CSV on first run."
    if not path.exists():
        df = pd.DataFrame(False, index=pd.Index([today], name="date"),
                          columns=default_items)
        save_full(df, path)
        return df
    df = pd.read_csv(path, index_col=0)
    df = df.fillna(False).astype(bool)
    df.index = pd.Index([date.fromisoformat(d) for d in df.index], name="date")
    return df

# %% ../nbs/00_core.ipynb #f135df05
def window(
    full:pd.DataFrame,  # full history from `load_full`
    today:date,  # last day of the window
    days:int=10,  # window length
) -> pd.DataFrame:
    "Trailing `days`-day view ending today; dates missing from history are False."
    idx = [today - timedelta(days=i) for i in range(days - 1, -1, -1)]
    return full.reindex(pd.Index(idx, name="date"), fill_value=False)

# %% ../nbs/00_core.ipynb #3700c7f7
ARCHIVE_PREFIX = "~"  # leading marker on the column name of an archived item

# %% ../nbs/00_core.ipynb #814d8c80
def is_archived(
    name:str,  # column name as stored in the CSV header
) -> bool:
    "True when the column name carries the archive marker."
    return name.startswith(ARCHIVE_PREFIX)

# %% ../nbs/00_core.ipynb #3080feee
def display_name(
    name:str,  # column name as stored in the CSV header
) -> str:
    "Item name without the archive marker."
    return name[len(ARCHIVE_PREFIX):] if is_archived(name) else name

# %% ../nbs/00_core.ipynb #8eaedd3c
def validate_name(
    name:str,  # candidate item name (display form, no marker)
    existing:list,  # current column names, archived ones included
):
    "Raise ValueError when `name` would corrupt the CSV, break routing, or collide."
    if not name:
        raise ValueError("empty name")
    if is_archived(name):
        raise ValueError(f"leading {ARCHIVE_PREFIX!r} is reserved for archived items")
    bad = set(',"/\n\r') & set(name)  # CSV parsing / path routing (DESIGN.md §5)
    if bad:
        raise ValueError(f"forbidden characters: {''.join(sorted(bad))!r}")
    if name in (display_name(c) for c in existing):
        raise ValueError(f"duplicate: {name}")

# %% ../nbs/00_core.ipynb #393bc631
def ordered_items(
    df:pd.DataFrame,  # ledger frame
) -> list:
    "Column names for display: active items first, then archived, each in column order."
    cols = list(df.columns)
    return [c for c in cols if not is_archived(c)] + [c for c in cols if is_archived(c)]

# %% ../nbs/00_core.ipynb #36edf992
def add_item(
    df:pd.DataFrame,  # ledger frame
    name:str,  # new item name
) -> pd.DataFrame:
    "New item as the last column; every existing day reads False."
    validate_name(name, list(df.columns))
    out = df.copy()
    out[name] = False
    return out

# %% ../nbs/00_core.ipynb #53beca0f
def _column(
    df:pd.DataFrame,  # ledger frame
    name:str,  # display name (marker optional)
) -> str:
    "Stored column name for a display name; KeyError when absent."
    for c in df.columns:
        if c == name or display_name(c) == name:
            return c
    raise KeyError(name)

def rename_item(
    df:pd.DataFrame,  # ledger frame
    old:str,  # current display name
    new:str,  # new display name
) -> pd.DataFrame:
    "Rename keeping history; an archived item stays archived."
    col = _column(df, old)
    validate_name(new, [c for c in df.columns if c != col])
    if is_archived(col):
        new = ARCHIVE_PREFIX + new
    return df.rename(columns={col: new})

# %% ../nbs/00_core.ipynb #00ebe02b
def set_archived(
    df:pd.DataFrame,  # ledger frame
    name:str,  # display name
    flag:bool,  # True = archive, False = restore
) -> pd.DataFrame:
    "Add or remove the archive marker; no-op when already in that state."
    col = _column(df, name)
    if is_archived(col) == flag:
        return df
    new = ARCHIVE_PREFIX + col if flag else display_name(col)
    return df.rename(columns={col: new})

# %% ../nbs/00_core.ipynb #70fbed1f
def rate_30d(
    full:pd.DataFrame,  # full history from `load_full`
    item:str,  # column name
    today:date,  # last day of the 30-day window
) -> float:
    "Fraction of the trailing 30 days (ending today) on which the item was checked."
    return float(window(full, today, 30)[item].mean())
